### ISSUE TITLE
[BUG] ログイン時に遷移しない

### ISSUE THREAD

**Issue by Ryoga-exe** [kss-pc-club/KSS-Fes-Admin#30]
## 🤨 起こっている問題
- `/login` からログインすると自動で `/` や `/admin` などに遷移しない

## 😀 期待する見せ方・挙動
- 自動で遷移するようにする

## 👀 起こっている問題の再現手段
1. ログアウトする
2. ログインする

## 🖥 動作環境・ブラウザ
- Chrome on Window / Android

**Comment by a01sa01to** [comment]
再現に成功しました、問題コードはここら辺かも。
直しておきます
https://github.com/kss-pc-club/KSS-Fes-Admin/blob/main/src/firebase.ts#L79-L93

**Comment by a01sa01to** [comment]
（直ってなかったらこっそりReopenしてね...）
